/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package overlay;

public class App {

    public String getGreeting() {
        return "Baibai";
    }

    public static void main(String[] args) {
        ClientListener cl = new ClientListener();
        int mode = Integer.parseInt(args[0]);
        try {
            if (mode == 0) {
                Send.run();
            } else {
                Recv.run();
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println(e.toString());
        }
        System.out.println(new App().getGreeting());
    }
}
