/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package overlay;

import java.io.IOException;
import java.util.concurrent.TimeoutException;

public class App {

    public String getGreeting() {
        return "Baibai";
    }

    public static void main(String[] args) throws IOException, TimeoutException {
        int physicalID = 0;
        int[][] physicalTopology = { {0, 1}, {1, 0}};
        String exchangeName = "defaultExchange";

        ClientListener cl = new ClientListener();
        cl.start();
    }
}
